version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: updates
  ignore:
  - dependency-name: com.github.scribejava:scribejava-apis
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: com.puppycrawl.tools:checkstyle
    versions:
    - "8.39"
    - "8.40"
    - "8.41"
    - 8.41.1
  - dependency-name: org.json:json
    versions:
    - "20201115"
